# Generated by Django 6.0.5 on 2026-06-03 05:18

from django.db import migrations, models

def populate_inquiry_numbers(apps, schema_editor):
    Consultation = apps.get_model('consultations', 'Consultation')
    User = apps.get_model('users', 'CustomUser')
    
    for user in User.objects.all():
        consultations = Consultation.objects.filter(user=user).order_by('created_at', 'id')
        for index, consultation in enumerate(consultations, start=1):
            consultation.inquiry_number = index
            consultation.save(update_fields=['inquiry_number'])

def rollback_inquiry_numbers(apps, schema_editor):
    Consultation = apps.get_model('consultations', 'Consultation')
    Consultation.objects.all().update(inquiry_number=None)

class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='inquiry_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_inquiry_numbers, rollback_inquiry_numbers),
    ]
