# Generated by Django 6.0.5 on 2026-06-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_inquiry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicenote',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='voicereply',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_replies', to='consultations.consultation'),
        ),
    ]
