# Generated by Django 6.0.5 on 2026-06-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
