# Generated by Django 6.0.5 on 2026-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
